# ----------------------------------------------------
# TAHAP 1: BUILDER
# ----------------------------------------------------
FROM node:20-slim AS builder

WORKDIR /app
COPY package.json package-lock.json ./ 
RUN npm install --legacy-peer-deps
ARG CACHEBUST_V1=1
COPY . .
RUN npm run build


# ----------------------------------------------------
# TAHAP 2: RUNNER (Node.js Standalone)
# ----------------------------------------------------
FROM node:20-slim AS runner

# 1. User non-root
RUN addgroup --gid 1001 nodejs
RUN adduser --uid 1001 --ingroup nodejs --shell /bin/sh --disabled-password nodejs

# 2. Salin output STANDALONE
WORKDIR /app
COPY --from=builder /app/public ./public
# 🚨 KOREKSI: Salin server.js dan folder yang dibutuhkan
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/package.json ./ 

# 3. Tetapkan Lingkungan
ENV PORT 3000
ENV NODE_ENV production

# 🚨 TAMBAHAN KRITIS: Memberi tahu server untuk mendengarkan di semua IP
# Next.js 14+ sering membutuhkan host/hostname di set ke '0.0.0.0'
ENV HOSTNAME 0.0.0.0 

EXPOSE 3000

USER nodejs

# Perintah untuk menjalankan aplikasi
CMD ["node", "server.js"]